language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -f Dockerfile.dev -t levenglick/docker-react .

script:
  - docker run -e CI=true levenglick/docker-react npm run test -- --coverage --watchAll

